Repository FutureNorthants/northants-design-system, pull requests merged in 2022-05, with the labels that each got.

#175 Fix SectionLinks alt attribute
  src/library/structure/SectionLinks/SectionLinks.styles.js
  src/library/structure/SectionLinks/SectionLinks.test.tsx
  src/library/structure/SectionLinks/SectionLinks.tsx
Labels: bug

#176 Add aria-label to sort buttons in ServicesLinksList
  src/library/structure/ServicesLinksList/ServicesLinksList.tsx
Labels: enhancement

#185 Fix memorial homepage
  src/library/components/icons/services/CondolenceBookIconHover/Icon.tsx
  src/library/components/icons/services/RoyalWebsiteIconHover/Icon.tsx
  src/library/pages/MemorialPage/MemorialPage.stories.tsx
  src/library/pages/MemorialPage/MemorialPage.tsx
  src/library/pages/MemorialPage/MemorialPage.types.ts
  src/library/structure/MemorialHero/MemorialHero.stories.tsx
  src/library/structure/MemorialHero/MemorialHero.styles.js
  src/library/structure/MemorialHero/MemorialHero.tsx
  src/library/structure/NewsArticleFeaturedBlock/NewsArticleFeaturedBlock.storydata.js
  src/library/structure/ServicesLinksBoxed/ServicesLinksBoxed.tsx
Labels: bug

#182 Update storybook
  package-lock.json
  package.json
Labels: npm dependencies

#189 Rearranged header with css grid, added news link
  src/library/structure/Header/Header.stories.tsx
  src/library/structure/Header/Header.styles.js
  src/library/structure/Header/Header.test.tsx
  src/library/structure/Header/Header.tsx
  src/library/structure/Header/Header.types.ts
Labels: enhancement

#191 Clicking link in alert banner dismisses banner
  src/library/structure/AlertBanner/AlertBanner.stories.tsx
  src/library/structure/AlertBanner/AlertBanner.tsx
Labels: enhancement

#179 Contents list and next/previous navigation
  src/library/pages/ServicePageExample/ServicePageExample.stories.tsx
  src/library/pages/ServicePageExample/ServicePageExample.tsx
  src/library/structure/Contents/Contents.stories.tsx
  src/library/structure/Contents/Contents.storydata.ts
  src/library/structure/Contents/Contents.styles.js
  src/library/structure/Contents/Contents.test.tsx
  src/library/structure/Contents/Contents.tsx
  src/library/structure/Contents/Contents.types.ts
  src/library/structure/ContentsNavigation/ContentsNavigation.stories.tsx
  src/library/structure/ContentsNavigation/ContentsNavigation.styles.js
  src/library/structure/ContentsNavigation/ContentsNavigation.test.tsx
  src/library/structure/ContentsNavigation/ContentsNavigation.tsx
  src/library/structure/PageStructures.ts
Labels: enhancement

#195 Fix for search suggestions in the header
  src/library/structure/Header/Header.styles.js
Labels: bug

#198 Make contents a h2
  package-lock.json
  package.json
  src/library/structure/Contents/Contents.tsx
Labels: bug

#200 Update to storybook 6.5
  package-lock.json
  package.json
  src/docs/1Introduction.stories.mdx
  src/docs/2PageStructure.stories.mdx
  src/docs/3GridSystem.stories.mdx
  src/docs/4Iconography.stories.mdx
  src/library/pages/ContentPage/ContentPage.tsx
Labels: npm dependencies
