Repository FutureNorthants/northants-design-system, pull requests merged in 2022-02, with the labels that each got.

#110 Optional breadcrumb spacing
  src/library/pages/ServiceLandingPageExample/ServiceLandingPageExample.stories.tsx
  src/library/pages/ServiceLandingPageExample/ServiceLandingPageExample.storydata.ts
  src/library/pages/ServiceLandingPageExample/ServiceLandingPageExample.tsx
  src/library/pages/ServiceLandingPageExample/ServiceLandingPageExample.types.ts
  src/library/structure/Breadcrumbs/Breadcrumbs.stories.tsx
  src/library/structure/Breadcrumbs/Breadcrumbs.styles.js
  src/library/structure/Breadcrumbs/Breadcrumbs.test.tsx
  src/library/structure/Breadcrumbs/Breadcrumbs.tsx
  src/library/structure/Breadcrumbs/Breadcrumbs.types.ts
Labels: bug

#112 Feature/image component
  package-lock.json
  package.json
  src/index.ts
  src/library/pages/ServicePageExample/ServicePageExample.tsx
  src/library/slices/Image/Image.stories.tsx
  src/library/slices/Image/Image.styles.js
  src/library/slices/Image/Image.test.tsx
  src/library/slices/Image/Image.tsx
  src/library/slices/Image/Image.types.ts
Labels: enhancement

#113 Add Promotions slice
  src/index.ts
  src/library/pages/ContentPage/ContentPage.tsx
  src/library/slices/Promotions/Promotions.stories.tsx
  src/library/slices/Promotions/Promotions.tsx
  src/library/structure/PromoBanner/PromoBanner.styles.js
  src/library/structure/PromoBlock/PromoBlock.storydata.ts
  src/library/structure/PromoBlock/PromoBlock.styles.js
Labels: enhancement

#115 Add optional images to section links
  .github/dependabot.yml
  package-lock.json
  package.json
  src/library/structure/SectionLinks/SectionLinks.stories.tsx
  src/library/structure/SectionLinks/SectionLinks.storydata.tsx
  src/library/structure/SectionLinks/SectionLinks.styles.js
  src/library/structure/SectionLinks/SectionLinks.test.tsx
  src/library/structure/SectionLinks/SectionLinks.tsx
  src/library/structure/SectionLinks/SectionLinks.types.ts
Labels: enhancement

#122 Update all dependencies to latest versions
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
Labels: npm dependencies

#124 Add parks icons
  src/library/components/icons/services/Charity/Icon.stories.tsx
  src/library/components/icons/services/Charity/Icon.tsx
  src/library/components/icons/services/CharityHover/Icon.stories.tsx
  src/library/components/icons/services/CharityHover/Icon.tsx
  src/library/components/icons/services/Flower/Icon.stories.tsx
  src/library/components/icons/services/Flower/Icon.tsx
  src/library/components/icons/services/FlowerHover/Icon.stories.tsx
  src/library/components/icons/services/FlowerHover/Icon.tsx
  src/library/components/icons/services/ParkEvent/Icon.stories.tsx
  src/library/components/icons/services/ParkEvent/Icon.tsx
  src/library/components/icons/services/ParkEventHover/Icon.stories.tsx
  src/library/components/icons/services/ParkEventHover/Icon.tsx
  src/library/components/icons/services/Parking/Icon.stories.tsx
  src/library/components/icons/services/Parking/Icon.tsx
  src/library/components/icons/services/ParkingHover/Icon.stories.tsx
  src/library/components/icons/services/ParkingHover/Icon.tsx
  src/library/components/icons/services/ServicesIcons.ts
Labels: enhancement

#130 Bugfix/google map styles overwritten
  package-lock.json
  src/library/pages/ContentPage/ContentPage.tsx
  src/library/slices/GoogleMap/GoogleMap.styles.js
Labels: bug, npm dependencies

#134 Fix Google Map embed regex check for Safari
  src/library/slices/GoogleMap/GoogleMap.tsx
Labels: bug

#136 Fix Google Maps accessibility warnings
  src/library/slices/GoogleMap/GoogleMap.styles.js
  src/library/slices/GoogleMap/GoogleMap.tsx
Labels: bug

#121 Feature/roads highways icons
  src/library/components/HeadingWithIconLink/HeadingWithIconLink.stories.tsx
  src/library/components/HeadingWithIconLink/HeadingWithIconLink.styles.js
  src/library/components/HeadingWithIconLink/HeadingWithIconLink.test.tsx
  src/library/components/HeadingWithIconLink/HeadingWithIconLink.tsx
  src/library/components/HeadingWithIconLink/HeadingWithIconLink.types.ts
  src/library/components/icons/services/AccessibleParking/Icon.stories.tsx
  src/library/components/icons/services/AccessibleParking/Icon.tsx
  src/library/components/icons/services/AccessibleParkingHover/Icon.stories.tsx
  src/library/components/icons/services/AccessibleParkingHover/Icon.tsx
  src/library/components/icons/services/Bollard/Icon.stories.tsx
  src/library/components/icons/services/Bollard/Icon.tsx
  src/library/components/icons/services/BollardHover/Icon.stories.tsx
  src/library/components/icons/services/BollardHover/Icon.tsx
  src/library/components/icons/services/BusIcon/Icon.stories.tsx
  src/library/components/icons/services/BusIcon/Icon.tsx
  src/library/components/icons/services/BusIconHover/Icon.stories.tsx
  src/library/components/icons/services/BusIconHover/Icon.tsx
  src/library/components/icons/services/BusPass/Icon.stories.tsx
  src/library/components/icons/services/BusPass/Icon.tsx
  src/library/components/icons/services/BusPassHover/Icon.stories.tsx
  src/library/components/icons/services/BusPassHover/Icon.tsx
  src/library/components/icons/services/Highway/Icon.stories.tsx
  src/library/components/icons/services/Highway/Icon.tsx
  src/library/components/icons/services/HighwayHover/Icon.stories.tsx
  src/library/components/icons/services/HighwayHover/Icon.tsx
  src/library/components/icons/services/ParkingTicket/Icon.stories.tsx
  src/library/components/icons/services/ParkingTicket/Icon.tsx
  src/library/components/icons/services/ParkingTicketHover/Icon.stories.tsx
  src/library/components/icons/services/ParkingTicketHover/Icon.tsx
  src/library/components/icons/services/Pothole/Icon.stories.tsx
  src/library/components/icons/services/Pothole/Icon.tsx
  src/library/components/icons/services/PotholeHover/Icon.stories.tsx
  src/library/components/icons/services/PotholeHover/Icon.tsx
  src/library/components/icons/services/Report/Icon.stories.tsx
  src/library/components/icons/services/Report/Icon.tsx
  src/library/components/icons/services/ReportHover/Icon.stories.tsx
  src/library/components/icons/services/ReportHover/Icon.tsx
  src/library/components/icons/services/RoadWorks/Icon.stories.tsx
  src/library/components/icons/services/RoadWorks/Icon.tsx
  src/library/components/icons/services/RoadWorksHover/Icon.stories.tsx
  src/library/components/icons/services/RoadWorksHover/Icon.tsx
  src/library/components/icons/services/ServicesIcons.ts
  src/library/structure/ServicesLinksList/ServicesLinksList.styles.js
  src/library/structure/ServicesLinksList/ServicesLinksList.test.tsx
  src/library/structure/ServicesLinksList/ServicesLinksList.tsx
Labels: enhancement

#129 Allow file downloads to be marked as archived
  src/library/components/FileDownload/FileDownload.stories.tsx
  src/library/components/FileDownload/FileDownload.test.tsx
  src/library/components/FileDownload/FileDownload.tsx
  src/library/components/FileDownload/FileDownload.types.ts
Labels: enhancement

#137 Make PromoBanner image clickable, add test
  src/library/structure/PromoBanner/PromoBanner.stories.tsx
  src/library/structure/PromoBanner/PromoBanner.storydata.tsx
  src/library/structure/PromoBanner/PromoBanner.styles.js
  src/library/structure/PromoBanner/PromoBanner.test.tsx
  src/library/structure/PromoBanner/PromoBanner.tsx
  src/library/structure/PromoBanner/PromoBanner.types.ts
Labels: enhancement
