Repository FutureNorthants/northants-design-system, pull requests merged in 2025-02, with the labels that each got.

#562 Added Auto-complete=email attrib to Email input
  src/library/structure/RateThisPage/RateThisPage.tsx
Labels: bug, accessibility

#559 Check inquest appointment type includes the hearing term
  src/library/slices/InquestSchedule/InquestSchedule.storydata.ts
  src/library/slices/InquestSchedule/InquestSchedule.tsx
  src/library/slices/InquestSchedule/InquestSchedule.types.ts
Labels: bug

#568 Updated Global Style Reset TSX to include anchor-tag link-item styling
  src/themes/GlobalStyleReset.tsx
Labels: accessibility
